# Generated by Django 6.0.2 on 2026-03-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_cpf', models.CharField(max_length=15)),
                ('employee_birth_date', models.DateField()),
                ('employee_function', models.CharField(max_length=255)),
                ('employee_sector', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(max_length=255)),
                ('adm_date', models.DateField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
