# Generated by Django 6.0.2 on 2026-02-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_comapany_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
