# Generated by Django 6.0.2 on 2026-02-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_password'),
        ('patients', '0005_alter_patient_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('exam_status', models.CharField(choices=[('pendente', 'Pendente'), ('coletado', 'Coletado'), ('aguardando_resultados', 'Aguardando Resultados'), ('pronto', 'Pronto')], max_length=255)),
                ('exam_status_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams_company', to='companies.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams_patient', to='patients.patient')),
            ],
        ),
    ]
