# Generated by Django 6.0.2 on 2026-03-05 22:15

import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(default='admissional', max_length=255)),
                ('exam_path', models.FileField(blank=True, max_length=255, null=True, upload_to=patients.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_company', to='companies.company')),
            ],
        ),
    ]
