# Generated by Django 6.0.2 on 2026-02-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('admissional', 'Admissional'), ('demisional', 'Demisional'), ('periodico', 'Periodico'), ('retorno_a_funcao', 'Retorno A Função'), ('mudanca_de_risco', 'Mudança De Riscos')], default='admissional', max_length=255)),
                ('exam_path', models.FileField(blank=True, null=True, upload_to='exams_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_company', to='companies.company')),
            ],
        ),
    ]
