# Generated by Django 6.0.2 on 2026-02-17 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 17, 14, 17, 24, 312041)),
        ),
    ]
