# Generated by Django 6.0.2 on 2026-02-18 16:39

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_birth_date_remove_patient_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='exam_path',
            field=models.FileField(blank=True, null=True, upload_to=patients.models.user_directory_path),
        ),
    ]
