# Generated by Django 6.0.2 on 2026-02-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_exam_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='exam_type',
            field=models.CharField(default='admissional', max_length=255),
        ),
    ]
